name: GitHub Profile 3D Contributions updated
description: Generate profile 3D Contributions updated
author: xcaro

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
